# .air.toml
# [1] 基础配置
root = "."
tmp_dir = "tmp"

# [2] 文件监听设置
include_ext = ["go", "yaml"]
exclude_dir = ["tmp", "vendor", "node_modules"]

# [3] 热重载延迟设置（核心！）
# 修改后延迟 500 毫秒再重启，避免频繁触发
delay = 500

# [4] 运行设置
[build]
cmd = "go run cmd/main.go"
bin = "tmp/main${GOEXE}"  # GOEXE 会自动加上.exe
log = "stdout"

[log]
time = true
